### ISSUE TITLE
Optimize svg files

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/seb-pictograms#16]
Svg file sizes could be reduced by optimizing them with something like: https://jakearchibald.github.io/svgomg/

Might even be some command line tool for it:)

**Comment by hjalmers** [comment]
I noticed that the generate svg for this lib is around 200 kb and one font is 50 kb! So I think there's room for improvement as a single optimized pictogram is about 230 bytes only!

**Comment by ForkInSpace** [comment]
@hjalmers svg files have been optimized and can be individually imported and used as of the latest release (v1.3.0).
I've used imagemin-svgo pkg which is what your proposed svgomg is using under the hood. 
Optimized svg pictogram sizes range from 155 bytes to over 1kb (in few cases). 

I'm closing this issue. Feel free to reopen
