### ISSUE TITLE
Can't resolve 'fonts/seb-pictograms.svg'

### ISSUE THREAD

**Issue by OskarWalinder** [sebgroup/seb-pictograms#17]
I had problem with importing in my angular application.
I tried with this:
@import "@sebgroup/seb-pictograms/pictograms.scss" in my style.scss.

This was the error:
"CssSyntaxError: C:\Repos\ApplicationName\node_modules\@sebgroup\seb-pictograms\pictograms.scss:7:9: Can't resolve 'fonts/seb-pictograms.svg' in 'C:\Repos\ApplicationName\src'".

**Comment by sauliuspaukstys** [comment]
You should add @sebgroup/seb-pictograms/pictograms.scss to angular.json
We will keep looking for a way on how to make it work in different ways
