### ISSUE TITLE
Rename SVG to reflect their usage

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/seb-pictograms#18]
## Description
Please use SVG names instead of arbitrary names with incremental identifiers. It is much easier for users to use, see the examples below:
This is how it can be imported at the moment:
```ts
const chatMan: string = require("@sebgroup/seb-pictograms/svg/regular/91-Picto-Regular_black.svg");
```
This is how I expect it to be imported:
```ts
const chatMan: string = require("@sebgroup/seb-pictograms/svg/regular/chat-man.svg");
```

## Rationale
The reason to why I don't use the pictograms as a font is because:
- I don't want to load all svgs just to use one of them. Importing everything as font will cost `27.94 KB` while importing the SVG directly cost `901 B`.
- Some mobile browsers are design to not load custom fonts when the connection is slow, it will default back to something like `Arial` which doesn't have the character code provided and it will display an empty box 🔲 instead.

**Comment by ForkInSpace** [comment]
Will get back to you once I have time to properly look into this and explore possible avenues on how to resolve this.

**Comment by hjalmers** [comment]
Might be worth taking a look at https://github.com/sebgroup/seb-pictograms/issues/3 again:)

**Comment by ForkInSpace** [comment]
@yousifalraheem the svg files have been renamed and you should be able to import pictograms like you proposed
`const chatMan: string = require("@sebgroup/seb-pictograms/svg/regular/chat-man.svg");`

all svg files and fonts have also been optimized as of the latest release. 

as for the #3 @hjalmers 
What you're proposing, even though is a good idea, would basically require creating a new lib from scratch and and as much as I'd love to do that unfortunately I don't have time for this at the moment. 

In the mean time enjoy the latest release and feel free to report any bugs you might come across

I'm closing this. Feel free to reopen
